services:

  db:
    image: postgres
    container_name: ${POSTGRES_NAME}
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
     
  
  go:
    container_name: go
    build: ./req/go
    env_file: .env
    ports:
      - "8090:8090"

  nats:
    image: nats-streaming
    container_name: ${STAN_NAME}
    env_file: .env
    ports:
      - "4222:4222"
    command: "--cluster_id ${CLUSTER_ID}"
